!-----------------------------------------------------------------------
      integer MPI_COMM_WORLD, MPI_STATUS_SIZE, MPI_SUCCESS
      parameter(MPI_COMM_WORLD=0,MPI_STATUS_SIZE=5,MPI_SUCCESS=0)
      integer MPI_INTEGER, MPI_REAL, MPI_DOUBLE_PRECISION
      parameter(MPI_INTEGER=18,MPI_REAL=19,MPI_DOUBLE_PRECISION=20)
      integer MPI_COMPLEX, MPI_DOUBLE_COMPLEX, MPI_BYTE
      parameter(MPI_COMPLEX=22,MPI_DOUBLE_COMPLEX=23,MPI_BYTE=2)
      integer MPI_INTEGER4, MPI_REAL4, MPI_REAL8, MPI_LOGICAL
      parameter(MPI_INTEGER4=MPI_INTEGER,MPI_LOGICAL=MPI_INTEGER)
      parameter(MPI_REAL4=MPI_REAL,MPI_REAL8=MPI_DOUBLE_PRECISION)
      integer MPI_2REAL, MPI_2DOUBLE_PRECISION, MPI_2INTEGER
      parameter(MPI_2REAL=35,MPI_2DOUBLE_PRECISION=36,MPI_2INTEGER=37)
      integer MPI_UNDEFINED
      parameter(MPI_UNDEFINED=-1)
      integer MPI_MAX, MPI_MIN, MPI_SUM, MPI_MAXLOC, MPI_MINLOC
      parameter(MPI_MAX=0,MPI_MIN=1,MPI_SUM=2,MPI_MAXLOC=4,MPI_MINLOC=5)
      integer MPI_SOURCE, MPI_TAG, MPI_ERROR, MPI_ERR_IN_STATUS
      parameter(MPI_SOURCE=1,MPI_TAG=2,MPI_ERROR=3,MPI_ERR_IN_STATUS=67)
      integer MPI_ANY_SOURCE, MPI_ANY_TAG, MPI_REQUEST_NULL
      parameter(MPI_ANY_SOURCE=-1,MPI_ANY_TAG=-1,MPI_REQUEST_NULL=-1)
      integer MPI_COMM_SELF, MPI_COMM_NULL, MPI_PROC_NULL
      parameter(MPI_COMM_SELF=1,MPI_COMM_NULL=-1,MPI_PROC_NULL=-3)
      integer MPI_MAX_PROCESSOR_NAME
      parameter(MPI_MAX_PROCESSOR_NAME=24)
      integer MPI_ERRORS_RETURN,MPI_ERRORS_ARE_FATAL
      parameter(MPI_ERRORS_RETURN=0,MPI_ERRORS_ARE_FATAL=1)
      double precision MPI_WTIME, MPI_WTICK
      external MPI_WTIME, MPI_WTICK
